Document: openvpn-server
Title: Debian openvpn-server Manual
Author: <insert document author here>
Abstract: This manual describes what openvpn-server is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/openvpn-server/openvpn-server.sgml.gz

Format: postscript
Files: /usr/share/doc/openvpn-server/openvpn-server.ps.gz

Format: text
Files: /usr/share/doc/openvpn-server/openvpn-server.text.gz

Format: HTML
Index: /usr/share/doc/openvpn-server/html/index.html
Files: /usr/share/doc/openvpn-server/html/*.html
