global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - host.docker.internal:2052

rule_files:
  - alertrules.yml

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["host.docker.internal:80"]

  - job_name: "alertmanager"
    static_configs:
      - targets: [ "host.docker.internal:2052" ]

  - job_name: "CA_NODE"
    static_configs:
      - targets: ["ec2-34-245-80-28.eu-west-1.compute.amazonaws.com:9100"]

  - job_name: "VPN_NODE"
    static_configs:
      - targets: [ "192.168.3.52:9100"]

  - job_name: "OPENVPN_STATISTICS"
    static_configs:
      - targets: [ "192.168.3.52:9176" ]
